### ISSUE TITLE
problems with including wasm to Safari 

### ISSUE THREAD

**Issue by SashaZhardetskaya** [nazar-pc/noise-c.wasm#4]
Hello. I develop extension for both chrome and safari. I've got a problem with lib in Safari. I import `noise-c.wasm` to background script. Every time get an error:  
`both async and sync fetching of the wasm failed`
While everything works fine in chrome.
I use noise-c.wasm 0.2.0 (However, this problem present in version 0.3.0 either)
Please, I'd be happy to receive any advice

**Comment by nazar-pc** [comment]
I only have Firefox and Chrome on my machine, so haven't seen this before. Anything else in logs (and Network tab)? Maybe path to wasm file is not correct for some reason.

**Comment by SashaZhardetskaya** [comment]
here what I see in console 
<img width="1000" alt="2018-08-28 11 49 36 am" src="https://user-images.githubusercontent.com/17475281/44712070-9ed0f980-aab8-11e8-8a2b-ae1b72eb9ba1.png">

noise-c.wasm didn't load to the browser according to network tab 
<img width="399" alt="2018-08-28 11 49 58 am" src="https://user-images.githubusercontent.com/17475281/44712350-3898a680-aab9-11e8-991c-71a80e8fbbe2.png">

How do you compile file so I could build with -s ASSERTIONS=1 ?

**Comment by nazar-pc** [comment]
I suggest you to look at Network tab to see where it tries to load wasm file from.

You can build it as follows:
1) Install emscripten, so that `emcc` is in your `$PATH`, emsdk is the easiest way to do this
2) `git clone git@github.com:nazar-pc/noise-c.wasm.git`
3) `cd noise-c.wasm`
4) `npm i`
5) `npm run vendor`
6) Update `gulpfile.js` with parameters you want to pass to Emscripten, similarly to those that are already there
7) `npm run build`

**Comment by SashaZhardetskaya** [comment]
Thanks
Unfortunately assertions didn't help a lot
<img width="1004" alt="2018-08-29 12 50 32 pm" src="https://user-images.githubusercontent.com/17475281/44840175-336a6180-ac49-11e8-9935-70a3c0142271.png">

**Comment by SashaZhardetskaya** [comment]
Btw, the request to download shows after refreshing network tab in devtools 
However url is correct

<img width="1002" alt="2018-08-30 11 41 42 am" src="https://user-images.githubusercontent.com/17475281/44841286-ab398b80-ac4b-11e8-931a-3b17b28864ed.png">
<img width="997" alt="2018-08-30 11 42 43 am" src="https://user-images.githubusercontent.com/17475281/44841297-b68cb700-ac4b-11e8-9622-fbf6a3bba620.png">
<img width="993" alt="2018-08-30 11 44 07 am" src="https://user-images.githubusercontent.com/17475281/44841324-c3a9a600-ac4b-11e8-9c41-59631483d79e.png">

I also discovered that WebAssembly object has different interface for chrome and safari

**Comment by nazar-pc** [comment]
Did you use `.ready()` method in version 0.2 to make sure library is properly loaded?
I known Safari is strange, but haven't seen anyone complaining about it in Emscripten's repository.

**Comment by SashaZhardetskaya** [comment]
We found the problem. 'noise-c.wasm' file has to be loaded from server by link. Safari extension tries to load wasm file locally, but js file generated by Emscripten threw an error
