### ISSUE TITLE
(Wasm) C code in javascript or code javascript in C

### ISSUE THREAD

**Issue by signgitgit** [nazar-pc/noise-c.wasm#6]
Hello,

Please where is the best methode :

Creat all my game with C code and convert it to wasm. 
Or
Coding  the most part of the game in C and import some code from javascript.
Or
Coding the most part of the game in javascript and import some code from C.

Thanks in advance.

**Comment by nazar-pc** [comment]
Wow, I'm not a game developer. My guess would be write most of it in C with Open GL and then compile with Emscripten, but I really don't know for sure.
