### ISSUE TITLE
Support for never revisions

### ISSUE THREAD

**Issue by richardhopton** [nazar-pc/noise-c.wasm#9]
How can I go about using this library with a more recent version of Noise specification?

https://github.com/rweather/noise-c/tree/rev32

**Comment by nazar-pc** [comment]
Gulpfile has build steps, package.json corresponding scripts to download and builds thins. So install Emscripten, try to compile against newer release and see if any of the APIs has changed since. There is exact commit used to build this, you can see the diff between that and latest version.

**Comment by richardhopton** [comment]
Can you confirm the version of emscripten you used? I'm getting an error about 
```
emcc: error: `EMMAKEN_CFLAGS` is no longer supported, please use `EMCC_CFLAGS` instead
```

Edit: I made a tweak to the gulpfile to use EMCC_CFLAGS and it seemed to run...

**Comment by richardhopton** [comment]
Okay, it's failing with:-
```
building:ERROR: Closure compiler run failed:

building:ERROR: /var/folders/4v/8rxwtf1j7hdd85_nlq05418h0000gn/T/emscripten_temp_x1gt2hjy/noise-c.jso4.js:769:18: ERROR - [JSC_UNDEFINED_VARIABLE] variable buffer is undeclared
  769|    return (new as(buffer, pointer, size / as.BYTES_PER_ELEMENT)).slice();
                         ^^^^^^
```
1 error(s), 0 warning(s)

I can see that line in `src/bytes_allocation.js`

**Comment by richardhopton** [comment]
I made a branch with what I've tried. Appreciate any help you give or suggestions you can offer:-
https://github.com/richardhopton/noise-c.wasm/tree/rev32

**Comment by nazar-pc** [comment]
Well, you'll have to figure it out on your own I'm afraid because helping would be equivalent to do it myself and I don't have time for it unfortunately, neither I care too much about this repo anymore (I'm mostly working with Rust these days).

**Comment by richardhopton** [comment]
Okay - I understand. Maybe marking the archive as abandoned might be better if you are unable/unwilling to support it moving forward. In the meantime, can you at least comment on the utility of `bytes_allocation` and if it can just be removed?

**Comment by nazar-pc** [comment]
It is used for allocation of bytes for use with C code. For instance if you want to send a string to WASM, you can't just use `String`. See where it is called from, context should be helpful in understanding.

As long as you want to call into WASM you can't remove those. I mean you'll have to use some kind of replacement code at least.

**Comment by richardhopton** [comment]
Oh okay. So marhalling JS strings into C... That's helpful context. 

The error indicates this code is attempting to access a buffer that has not been defined, and I cannot see a buffer definition anywhere... I tried to run the build step on your unchanged master branch pointing at the same commit you ran it against years ago and it failed with the same error. Perhaps it's caused by a change in emscripten or something. Maybe I'll try to hunt down an older version of emscripten that will work with your code before I try to make my changes.

**Comment by nazar-pc** [comment]
Yes, I think Emscripten have have had some breaking changes during last few years, but there should be some way to achieve the same still.

**Comment by richardhopton** [comment]
Hmmm... found this in the emscripten changelog:-
- The buffer `JavaScript` variable was removed. This underlying buffer is still accessible via `wasmMemory.buffer` or `HEAPXX.buffer`

interesting

**Comment by richardhopton** [comment]
I managed to get this working - thanks for the assist.
